apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - namespace.yaml
  - ../../base
  - nodeport.yaml

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/instance: redis-dev
      app.kubernetes.io/environment: dev
