apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/instance: redis-prod
    app.kubernetes.io/environment: prod
type: Opaque
data:
  redis-password: Q0hBTkdFLU1FLVBST0QtUEFTU1dPUkQ=  # SANITIZED
